### ISSUE TITLE
Food Model

### ISSUE THREAD

**Issue by royyandzakiy** [keychera/AquaAesthetic#10]
create Food Model

**Comment by royyandzakiy** [comment]
Baru membuat `class Food` dengan menduplikat model lain

lanjutkan `moveFood();` sesuai dengan logic pergerakan Food

**Comment by keychera** [comment]
dengan ini dan adanya `movingObject` class mungkin `fishController` akan lebih digeneralisasi menjadi `movingObjectController`

**Comment by keychera** [comment]
continued and extended by the issue #17
