### ISSUE TITLE
.wav files uploaded makes git clone takes really long

### ISSUE THREAD

**Issue by keychera** [keychera/AquaAesthetic#13]
solution: will temporarily delete uploaded .wav and reupload them later when needed, also probably will use smaller .mp3  version instead because [git is very bad at tracking big files (probably more than 5mbs) ](http://stackoverflow.com/a/3055693)

**Comment by teaolivia** [comment]
ok

**Comment by teaolivia** [comment]
actually it is fine on my side haha, but if you burdened, I don't mind.

**Comment by keychera** [comment]
the big file is not properly deleted, it is still saved in the past commit
git clone and git pull still takes really long
will do what [this tool has to offer](https://rtyley.github.io/bfg-repo-cleaner/)

**Comment by keychera** [comment]
the tool worked well
all files that are bigger than 5MB is removed
please don't upload things that are not needed urgently, especially big files
a more subtle [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) principle has been a PSA
