### ISSUE TITLE
we NEED more classes

### ISSUE THREAD

**Issue by keychera** [keychera/AquaAesthetic#20]
2 - 6 abstract class
>15 real class

**Comment by teaolivia** [comment]
Are those classes made or classes in required?

**Comment by fildahananda** [comment]
is it done? so i can fix the class diagram

**Comment by keychera** [comment]
Current number
Abstract = 1 abstract(Model) + 1 interface(Controller)
Real = 1 View + 3 Model + 6 Controller + 1 Main

**Comment by keychera** [comment]
Hmm jadi belum nyampe target
