### ISSUE TITLE
all SubController doesn't yet handle object destruction

### ISSUE THREAD

**Issue by keychera** [keychera/AquaAesthetic#23]
they can addNewEntity but not yet deleteSpecificEntity

**Comment by keychera** [comment]
this is not what I mean
```Java
@Override
public void destroy() {
	// TODO Auto-generated method stub
	fishes = null;
}
```

what I do mean is deleting specific entity when needed (seperti saat ikan makan sebuah makanan, makanan tersebut dihapus dari list biar nggak diproses)

`List` class have several helpful methods, `remove(int e)`, `remove(Object o)`, `removeAll()`, but it's more than just using that

**Comment by teaolivia** [comment]
ok

**Comment by keychera** [comment]
all `SubControllers` that handles entities now have a method to remove obsolete entities
on commit 5f946efc16e759cc1710e38b332e2cb110e22553 branch `testingFish`
