### ISSUE TITLE
Unit Tests (see #24)

### ISSUE THREAD

**Issue by teaolivia** [keychera/AquaAesthetic#28]
Can @royyandzakiy or @fildfreeze help me with unit tests?

use branch `unitTesting`

**Comment by teaolivia** [comment]
see #24

**Comment by keychera** [comment]
untuk unit testing, mungkin yang nggak bisa ada JUnit nya itu
--GameLoopController -- karena dia itu multithreading
--GuiController -- karena dia itu ngurusin layout aplikasinya
--MainController -- karena dia cuma inisialisasi
dan setiap kelas di View
