### ISSUE TITLE
Don't forget to add comments

### ISSUE THREAD

**Issue by teaolivia** [keychera/AquaAesthetic#29]
see #24 

Example of comment style: 
[THE BULLETS ARE ORIGINALLY ASTERISKS]
/**
* The HelloWorld program implements an application that
* simply displays "Hello World!" to the standard output.
*
* @author  Zara Ali
* @version 1.0
* @since   2014-03-31 
*/

for tags you can Google it

**Comment by royyandzakiy** [comment]
should all classes have comments?

**Comment by teaolivia** [comment]
all in views, controllers, and models packages. Remember, excluding test packages as for now.

**Comment by teaolivia** [comment]
And all methods ideally ought to have comments.
