### ISSUE TITLE
Fish view

### ISSUE THREAD

**Issue by keychera** [keychera/AquaAesthetic#5]
the fish drawing logic, the default, for now, is just drawing an oval, embedded in the AquariumView class [here](https://github.com/keychera/AquaAesthetic/blob/bb8b5bf819c55bf614419d77ff8919a37863f576/src/views/AquariumView.java#L23-L30)

now we need a proper fish

**Comment by teaolivia** [comment]
Regarding fish view, anyone have an idea to not just move but also wagging tails while it moving?

**Comment by teaolivia** [comment]
I am trying to implement fps while its moving anw

**Comment by keychera** [comment]
anw? btw FPS implementation is also under the realm of issue #6 Multithreading that I'm about to study so please later specify how will it be implemented on this issue

regarding the fish wagging tails, hmm, itu masalah terpisah dan menurutku masih feasible  buat dipikirkan nanti, but cmiiw

**Comment by royyandzakiy** [comment]
@keychera I will try to use JLabels and ImageIcons for fish pictures, can you help me with the controllers to update the pictures every now and then?

**Comment by keychera** [comment]
try creating a separate controller and then I will try control that controller

**Comment by keychera** [comment]
btw kalo ada working solution tapi belum integrated push aja ke branch baru aja

oiya dan komen atas dan coba buatnya subcontroller, ada interfacenya (walaupun cuma satu method sih)

**Comment by keychera** [comment]
btw kalo `drawImage` masih belum feasible, untuk `Fish View` (dan `View` lain secara general), pake yang lebih direct aja, panggil `drawOval` dan `drawRect` beberapa kali untuk membentuk ikan di setiap iterasinya
