### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by keychera** [keychera/AquaAesthetic#6]
_DANg I forgot about this one_
the controller should implement multithreading

**Comment by teaolivia** [comment]
For concurrency:
- the multitasking of the fish
- movement of the coin
- calculating money collected(?)
- BGM and sound effects

**Comment by keychera** [comment]
this thing is more challenging than I initially thought

**Comment by teaolivia** [comment]
Also if background sound inserted, it is suggested that we implements concurrency on MainController haha

**Comment by keychera** [comment]
finally, I understand and I discovered that we can use a concurrency design pattern that is already encapsulated in one class....
`The `[`SwingWorker`](http://www.javaadvent.com/2012/12/multi-threading-in-java-swing-with-swingworker.html)` class`
...
now it's time for ...
- [x] study the thing
- [x] implement the thing!

**Comment by keychera** [comment]
the default structure for multithreading using `SwingWorker` is done, starting from commit 5556b5d6adde712a980db512ad9629bdb3431227 from branch `testingMultithreading`

**Comment by keychera** [comment]
multithreading is now implemented on branch `testingFish`
