### ISSUE TITLE
Value of Coin

### ISSUE THREAD

**Issue by teaolivia** [keychera/AquaAesthetic#9]
- Gold : 50
- Silver : 30
- Copper : 10

**Comment by keychera** [comment]
dari spek spek milestone yang ku definisiin, feature coin kayak Insaniquarium itu beyond v3 sih
cek Milestone deh

**Comment by keychera** [comment]
dan value itu lebih ke game rule sih jadi fine fine aja value itu untuk sekarang

**Comment by teaolivia** [comment]
jadi samain dulu semua lah ya
